# Generated by Django 2.0.13 on 2019-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.CharField(max_length=10)),
                ('acertos', models.CharField(max_length=10)),
                ('erros', models.CharField(max_length=10)),
            ],
        ),
    ]
