# Generated by Django 2.0.13 on 2019-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='equacao',
            field=models.CharField(default='+', max_length=50),
            preserve_default=False,
        ),
    ]
