# Generated by Django 2.0.9 on 2019-05-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_score_equacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('heroi', 'Super-Herói'), ('vilao', 'Super-Vilão')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('fala', models.TextField(max_length=120)),
                ('foto', models.ImageField(upload_to='personagem')),
            ],
        ),
    ]
