# Generated by Django 2.0.9 on 2019-05-31 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pessoa_user'),
        ('blog', '0003_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Aluno'),
            preserve_default=False,
        ),
    ]
