# Generated by Django 2.0.9 on 2019-05-31 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_score_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
