# Generated by Django 2.0.9 on 2019-06-12 00:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_score_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='foto',
            field=models.ImageField(upload_to=blog.models.Personagem.path),
        ),
    ]
