# Generated by Django 2.0.9 on 2019-06-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_resposta_certa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='questao',
        ),
        migrations.DeleteModel(
            name='Desafio',
        ),
    ]
