# Generated by Django 2.0.9 on 2019-06-12 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pessoa_user'),
        ('desafio', '0004_auto_20190611_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nivel', models.IntegerField()),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('answer_date', models.DateField()),
                ('init_time', models.TimeField(auto_now=True)),
                ('final_time', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Aluno')),
                ('questao', models.ManyToManyField(related_name='questao', to='desafio.Questao')),
            ],
        ),
    ]
