# Generated by Django 2.0.9 on 2019-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='des',
            name='questao',
            field=models.ManyToManyField(related_name='question', to='desafio.Questao'),
        ),
    ]
